New API cleanup
This makes two changes:

1. Remove `$saturation` and `$lightness` parameter defaults - if these
   are null you'll get compilation failures.

   ```
   Error: $map: 10deg is not a map.
     ╷
   7 │   $h: map.get($hsluv, "h");
     │       ^^^^^^^^^^^^^^^^^^^^
     ╵
     src/conversions/_lch.scss 7:7  from-hsluv()
     src/_conversions.scss 33:9     hsluv-rgb()
     src/_hsluv.scss 6:9            hsluv()
     demo.scss 4:12                 root stylesheet
   ```
2. Add a top level `/index.scss` file. This allows `@import "./node_modules/hsluv-sass"`
   instead of `@import "./node_modules/hsluv-sass/src/hsluv";`